(load (expand-file-name "lisp/boot.el" user-emacs-directory))

(add-to-list 'load-path (user-file "lisp"))
(load-file (user-file "lisp/autoloads.el"))
(add-to-list 'load-path (user-file "site-lisp"))
(load-file (user-file "site-lisp/autoloads.el"))

(setq custom-file (user-file "custom.el"))

(when (file-exists-p (user-file "before-init.el"))
  (load-file (user-file "before-init.el")))

(package-initialize)
(require 'packages)
(require 'conf/packages)
(if (not (file-exists-p package-user-dir))
    (conf/install-selected-packages))

(require 'boot)
(require 'tools)

(load-custom-file-if-exists)
(require 'conf/main)
(require 'conf/basic-editing)
(require 'conf/buffer-list)
(require 'conf/cc)
(require 'conf/clojure)
(require 'conf/completion)
(require 'conf/desktop)
(require 'conf/dired)
(require 'conf/ediff)
(require 'conf/emms)
(require 'conf/java)
(require 'conf/javascript)
(require 'conf/lisp)
(require 'conf/mode-line)
(require 'conf/org)
(require 'conf/projects)
(require 'conf/python)
(require 'conf/scilab)
(require 'conf/sql)
(require 'conf/vc)
(require 'conf/web)

(require 'conf/yasnippet)
(when (eq system-type 'cygwin)
  (require 'conf/cygwin))

(require 'server)
(unless (server-running-p)
  (server-start))

(when (file-exists-p (user-file "after-init.el"))
  (load-file (user-file "after-init.el")))
